from vacore import VACore
import subprocess, platform, os
# функция на старте
def start(core:VACore):
    manifest = {
        "name": "Открыть программу по настраиваемой команде",
        "version": "1.0",
        "require_online": False,

        "commands": {

        },

        "default_options": {
            "cmds": {
                "питон": "C:\\Python310\\python.exe", # путь для windows
                "паметры": "windows.immersivecontrolpanel_cw5n1h2txyewy!microsoft.windows.immersivecontrolpanel",
                "блокнот": "{1AC14E77-02E7-4E5D-B744-2EB1AE5198B7}\\notepad.exe", # название
                "корзина": "::{645FF040-5081-101B-9F08-00AA002F954E}",
                "планировщик заданий": "Microsoft.AutoGenerated.{40D5C9D0-AF1C-1ADC-3C79-992C0E52FF6E}",
                "сведения о системе": "{1AC14E77-02E7-4E5D-B744-2EB1AE5198B7}\\msinfo32.exe",
                "экранный диктор": "{1AC14E77-02E7-4E5D-B744-2EB1AE5198B7}\\narrator.exe",
                "ножницы": "{1AC14E77-02E7-4E5D-B744-2EB1AE5198B7}\\SnippingTool.exe",
                "параметры": "windows.immersivecontrolpanel_cw5n1h2txyewy!microsoft.windows.immersivecontrolpanel",
                "калькулятор": "Microsoft.WindowsCalculator_8wekyb3d8bbwe!App",
                "запись голоса": "Microsoft.WindowsSoundRecorder_8wekyb3d8bbwe!App",
                "диспетчер задач": "Microsoft.AutoGenerated.{600A9E7E-A9B2-0BEE-56C1-545351DEA529}",
                "этот компьютер": "Microsoft.Windows.Computer",
                "проводник": "Microsoft.Windows.Explorer",


                
            }
        }

    }
    return manifest

def start_with_options(core:VACore, manifest:dict):
    # модифицируем манифест, добавляя команды на основе options, сохраненных в файле
    cmds = {}
    cmdoptions = manifest["options"]["cmds"]
    print(cmdoptions)
    for cmd in cmdoptions.keys():
        cmds[cmd]  = (open_program, cmdoptions[cmd])
    manifest["commands"] = cmds
    return manifest

def open_program(core:VACore, phrase:str, param: str):
    try:
        if platform.system() == "Windows":
            if os.path.exists(param): # Если путь существует
                subprocess.run(('start', path), shell = True, stdout=subprocess.PIPE, check=True)
            else: # Тогда путь является названием
                subprocess.run(['powershell.exe', start_path_2], shell=True, stdout=subprocess.PIPE, check=True)
        elif platform.system() == 'Linux':
            pass
    except Exception:
        core.play_voice_assistant_speech("Ошибка при открытии программы")
  