# Плагин запуска, запускает встроенную в windows команду start, для Linux..
# Пути для windows: 
#   1. "C:\\Python310\\python.exe"   перед спец символами ставить "\". Открывает и папки
#   2. "calc"   Встроенные названия. 
#   3. "shell:appsfolder\\Microsoft.Windows.Computer", # В такоей форме shell:appsfolder\\{название}
# для linux: взято (https://github.com/aquaratixc/irene_va_plugins/blob/main/plugin_apprunner.py)

from vacore import VACore
import subprocess, platform, os

def start(core:VACore):
    manifest = {
        "name": "Запуск программы",
        "version": "1.1",
        "require_online": False,
        "commands": {
        },
        "default_options": {
            "cmds": {
                # примеры путей
                "питон": "C:\\Python310\\python.exe", 
                "калькулятор": "calc",       
                "блокнот": "shell:appsfolder\\{1AC14E77-02E7-4E5D-B744-2EB1AE5198B7}\\notepad.exe",        
                "этот компьютер": "shell:appsfolder\\Microsoft.Windows.Computer", 
                "паметры": "shell:appsfolder\\windows.immersivecontrolpanel_cw5n1h2txyewy!microsoft.windows.immersivecontrolpanel",
                "блокнот": "shell:appsfolder\\{1AC14E77-02E7-4E5D-B744-2EB1AE5198B7}\\notepad.exe", 
                "корзина": "shell:appsfolder\\::{645FF040-5081-101B-9F08-00AA002F954E}",
                "планировщик заданий": "shell:appsfolder\\Microsoft.AutoGenerated.{40D5C9D0-AF1C-1ADC-3C79-992C0E52FF6E}",
                "сведения о системе": "shell:appsfolder\\{1AC14E77-02E7-4E5D-B744-2EB1AE5198B7}\\msinfo32.exe",
                "экранный диктор": "shell:appsfolder\\{1AC14E77-02E7-4E5D-B744-2EB1AE5198B7}\\narrator.exe",
                "ножницы": "shell:appsfolder\\{1AC14E77-02E7-4E5D-B744-2EB1AE5198B7}\\SnippingTool.exe",
                "параметры": "shell:appsfolder\\windows.immersivecontrolpanel_cw5n1h2txyewy!microsoft.windows.immersivecontrolpanel",
                "запись голоса": "shell:appsfolder\\Microsoft.WindowsSoundRecorder_8wekyb3d8bbwe!App",
                "диспетчер задач": "shell:appsfolder\\Microsoft.AutoGenerated.{600A9E7E-A9B2-0BEE-56C1-545351DEA529}",
                "проводник": "shell:appsfolder\\Microsoft.Windows.Explorer",
                "соник": "C:\\GOG Games\\Sonic Adventure 2\\Launcher.exe",    
            }
        }
    }
    return manifest

def start_with_options(core:VACore, manifest:dict):
    cmds = {}
    cmdoptions = manifest["options"]["cmds"]
    for cmd in cmdoptions.keys():
        cmds[cmd]  = (start_program, cmdoptions[cmd])
    manifest["commands"] = cmds
    return manifest

def start_program(core:VACore, phrase:str, param: str):
    try:
        if platform.system() == "Windows":
            start_path = f'start "{param}"'
            subprocess.run(['powershell.exe', start_path], shell=True, stdout=subprocess.PIPE, check=True)
        elif platform.system() == 'Linux':
            # https://github.com/aquaratixc/irene_va_plugins/blob/main/plugin_apprunner.py
            subprocess.run(param.split(' '), stdout=subprocess.PIPE, check=True)
    except Exception:
        core.play_voice_assistant_speech("Ошибка при открытии программы")